"""renombre tabla producto model

Revision ID: 1931617a3c66
Revises: e0e44acf206a
Create Date: 2024-11-29 20:42:41.321925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1931617a3c66'
down_revision = 'e0e44acf206a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.rename_table
    op.rename_table('producto_model', 'productos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('productos', 'producto_model')
    # ### end Alembic commands ###
